"use strict";

const { contextBridge, ipcRenderer } = require("electron");

contextBridge.exposeInMainWorld("cttc", {
  pickFiles: (title, filters) => ipcRenderer.invoke("pick-files", title, filters),
  saveBinary: (defaultName, bytes) => ipcRenderer.invoke("save-binary", defaultName, bytes),
  readFile: (filePath) => ipcRenderer.invoke("read-file", filePath),
  saveJson: (defaultName, jsonText) => ipcRenderer.invoke("save-json", defaultName, jsonText),
  saveText: (defaultName, text) => ipcRenderer.invoke("save-text", defaultName, text),
  popout: (kind, id, view) => ipcRenderer.invoke("popout", kind, id, view),
  openHelp: (topic) => ipcRenderer.invoke("open-help", topic),
  onPopoutClosed: (cb) => ipcRenderer.on("popout-closed", (_e, msg) => cb(msg)),
  broadcastSync: (msg) => ipcRenderer.send("sync-broadcast", msg),
  onSync: (cb) => ipcRenderer.on("sync-broadcast", (_e, msg) => cb(msg)),
  onMenuAction: (cb) => ipcRenderer.on("menu-action", (_e, action) => cb(action)),
  onMainLog: (cb) => ipcRenderer.on("main-log", (_e, entry) => cb(entry)),
  onSplashStatus: (cb) => ipcRenderer.on("splash-status", (_e, text) => cb(text)),
  onAppShuttingDown: (cb) => ipcRenderer.on("app-shutting-down", () => cb()),
  menubarAction: (action) => ipcRenderer.invoke("menubar-action", action),
  submitSetup: (payload) => ipcRenderer.invoke("gateway-setup-submit", payload),
  onSetupLog: (cb) => ipcRenderer.on("setup-log", (_e, line) => cb(line)),
  addGateway: (payload) => ipcRenderer.invoke("gateway-add-submit", payload),
  saveGatewayEdit: (payload) => ipcRenderer.invoke("gateway-manage-save", payload),
  uninstallGateway: (entry) => ipcRenderer.invoke("gateway-manage-uninstall", entry),
  pickRecordingPath: () => ipcRenderer.invoke("pick-recording-path"),
  pickLogExportPath: (defaultName) => ipcRenderer.invoke("pick-log-export-path", defaultName),
  getRecordingScratchPath: () => ipcRenderer.invoke("get-recording-scratch-path"),
  writeBinaryFile: (filePath, bytes) => ipcRenderer.invoke("write-binary-file", filePath, bytes),
  getRecordingMarker: () => ipcRenderer.invoke("get-recording-marker"),
  setRecordingMarker: (marker) => ipcRenderer.invoke("set-recording-marker", marker),
  getGateways: () => ipcRenderer.invoke("get-gateways"),
  getSelectedContainers: (hostKey) => ipcRenderer.invoke("get-selected-containers", hostKey),
  setSelectedContainers: (hostKey, names) => ipcRenderer.invoke("set-selected-containers", hostKey, names),
  deleteSelectedContainers: (hostKey) => ipcRenderer.invoke("delete-selected-containers", hostKey),
  getConnectionInfo: () => ipcRenderer.invoke("get-connection-info"),
  redisCliRun: (argv) => ipcRenderer.invoke("redis-cli-run", argv),
  recordDockerHost: (dockerHostEntry) => ipcRenderer.invoke("record-docker-host", dockerHostEntry),
  switchGateway: (entry) => ipcRenderer.invoke("switch-gateway", entry),
  checkGateway: (entry) => ipcRenderer.invoke("check-gateway", entry),
  openActionBarWindow: () => ipcRenderer.invoke("open-action-bar-window"),
  closeActionBarWindow: () => ipcRenderer.invoke("close-action-bar-window"),
  triggerAction: (action) => ipcRenderer.send("action-bar-trigger", action),
  onRunAction: (cb) => ipcRenderer.on("run-action", (_e, action) => cb(action)),
  redockActionBar: () => ipcRenderer.send("action-bar-redock"),
  onActionBarRedock: (cb) => ipcRenderer.on("action-bar-redock", () => cb()),
  setPollInterval: (secs) => ipcRenderer.send("action-bar-poll-interval", secs),
  onSetPollInterval: (cb) => ipcRenderer.on("set-poll-interval", (_e, secs) => cb(secs)),
  setThemeMode: (mode) => ipcRenderer.send("set-theme-mode", mode),
  getLogCollectorSettings: () => ipcRenderer.invoke("get-log-collector-settings"),
  setLogCollectorEnabled: (enabled) => ipcRenderer.invoke("set-log-collector-enabled", enabled),
  shipLogs: () => ipcRenderer.invoke("ship-logs"),
  saveEventArtifact: (name, bytes, opts) => ipcRenderer.invoke("save-event-artifact", name, bytes, opts),
  listEventArtifacts: () => ipcRenderer.invoke("list-event-artifacts"),
});
