#!/bin/bash

# This script collects Docker container statistics periodically and logs them
# to a file.
log_file=${1:-"/tmp/temp.log"}

while true; do
    ts=$(date '+%Y-%m-%dT%H:%M:%S')
    sudo docker stats --no-stream --format "json" \
      | jq -c --arg ts "$ts" '. + {timestamp: $ts}'

    sleep 5
done