#!/usr/bin/env python3.11

import json
import sys
import time

from pathlib import Path


def main(
    filename: str | Path,
    output_file: str | Path | None = None,
    attempts: int = 5,
) -> None:
    failed_reading = True
    if output_file is None:
        output_file = "/dev/stdout"
    for _ in range(attempts):
        try:
            with open(filename, "r") as f:
                failed_reading = False
                data = f.read()

                json_output = [json.loads(entry) for entry in data.splitlines()]
                if output_file != "/dev/stdout":
                    with open(output_file, "r+") as f:
                        try:
                            current = json.loads(f.read())
                        except json.JSONDecodeError:
                            current = []
                        f.seek(0)
                        json.dump(current + json_output, f, separators=(",", ":"))
                else:
                    for entry in json_output:
                        sys.stdout.write(json.dumps(entry, indent=2) + "\n")
                break

        except IOError as e:
            print(f"IOError: {e}")
            time.sleep(4)  # Wait 4 seconds before retrying
        except json.JSONDecodeError as e:
            print(f"Error decoding JSON: {e}")
            failed_reading = True
            break
    if failed_reading:
        print(f"Failed to read/write file {filename} after {attempts} attempts.")


if __name__ == "__main__":
    main(
        sys.argv[1],
        output_file=sys.argv[2] if len(sys.argv) > 2 else None,
        attempts=int(sys.argv[3]) if len(sys.argv) > 3 else 5,
    )
